version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr > /dev/null"]
      interval: 10s
      retries: 10
    networks:
      - pimnet
    volumes:
      - sql_data:/var/opt/mssql

  pim-backend:
    build: .
    container_name: pim-backend
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PIM;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - pimnet

volumes:
  sql_data:

networks:
  pimnet:
    driver: bridge
